### ISSUE TITLE
Object of type 'PyObjectId' is not JSON serializable

### ISSUE THREAD

**Issue by congnghiakhiem** [mongodb-developer/mongodb-with-fastapi#3]
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "c:\python38\lib\site-packages\fastapi\applications.py", line 171, in __call__
    await super().__call__(scope, receive, send)
  File "c:\python38\lib\site-packages\starlette\applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\python38\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "c:\python38\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "c:\python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "c:\python38\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "c:\python38\lib\site-packages\starlette\routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "c:\python38\lib\site-packages\starlette\routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "c:\python38\lib\site-packages\starlette\routing.py", line 41, in app
    response = await func(request)
  File "c:\python38\lib\site-packages\fastapi\applications.py", line 120, in openapi
    return JSONResponse(self.openapi(root_path))
  File "c:\python38\lib\site-packages\fastapi\applications.py", line 103, in openapi
    self.openapi_schema = get_openapi(
  File "c:\python38\lib\site-packages\fastapi\openapi\utils.py", line 350, in get_openapi
    definitions = get_model_definitions(
  File "c:\python38\lib\site-packages\fastapi\utils.py", line 60, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic\schema.py", line 455, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 491, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 177, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 712, in pydantic.schema.encode_default
  File "pydantic\json.py", line 62, in pydantic.json.pydantic_encoder
TypeError: Object of type 'PyObjectId' is not JSON serializable

**Comment by judy2k** [comment]
Hi @congnghiakhiem - thanks for the bug report.

I'll look into this, but in the meantime, please could you comment with the output you get when you run `pip freeze` in your virtualenv, just in case this is a versioning problem. Thanks!

**Comment by congnghiakhiem** [comment]
Hi @judy2k. Here is the result of `pip freeze`

aiofiles==0.6.0
aioredis==1.3.1
amqp==5.0.6
astroid==2.4.2
async-timeout==3.0.1
bcrypt==3.2.0
billiard==3.6.4.0
celery==5.0.5
certifi==2020.4.5.2
cffi==1.14.5
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
colorama==0.4.3
configparser==5.0.2
crayons==0.4.0
cryptography==3.4.7
dnspython==2.1.0
ecdsa==0.14.1
email-validator==1.1.2
facebook-sdk==3.1.0
fastapi==0.58.0
h11==0.9.0
h2==3.2.0
hiredis==2.0.0
hpack==3.0.0
hstspreload==2020.6.16
httptools==0.1.1
httpx==0.11.1
hyperframe==5.2.0
idna==2.9
imgkit==1.2.2
isort==4.3.21
kombu==5.0.2
lazy-object-proxy==1.4.3
mccabe==0.6.1
motor==2.4.0
multidict==5.1.0
numpy==1.18.4
pandas==1.0.3
passlib==1.7.4
Pillow==8.2.0
prompt-toolkit==3.0.18
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
pydantic==1.5.1
pylint==2.5.3
pymongo==3.11.4
python-dateutil==2.8.1
python-jose==3.2.0
pytz==2020.1
requests==2.25.1
rfc3986==1.4.0
rsa==4.7.2
sanic==21.3.4
sanic-routing==0.6.2
selenium==3.141.0
six==1.14.0
sniffio==1.1.0
sseclient==0.0.27
starlette==0.13.4
Telethon==1.21.1
toml==0.10.1
urllib3==1.25.9
uvicorn==0.11.5
vine==5.0.0
wcwidth==0.2.5
webdriver-manager==3.4.1
websockets==8.1
wrapt==1.12.1

**Comment by ryoung-mbo** [comment]
Hi @congnghiakhiem See #6

**Comment by judy2k** [comment]
I've resolved this as part of #16. "_id" values are now coerced to `str` so that they serialize correctly.
